config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do
  mount Resque::Server, :at => "/resque"
  get "/oauth2callback", to: "uploads#update"
  mount RailsAdmin::Engine => "/adminmviehdkh", as: "rails_admin"

  root "movies#index"

  devise_for :users, only: :session, path: "", path_names: {sign_in: "@dminmoviehdkhlog_in"}

  resources :movies, only: [:index, :show]
  resources :categories, only: :show
  resources :requests, only: [:new, :create, :show]
  resources :years, only: :show
  resources :advertises, only: :index
  resources :searchs, only: :index
  resources :uploads, only: [:index, :update]
  resources :links, only: :index

  namespace :admin do
    resources :users
    resources :torrents, only: :index
    resources :exports, only: [:index, :create]
  end
end

app/views/shared/_announced.html.erb
<div class="container" id="announced">
  <table>
    <thead>
      <tr><th>■ If you can not see the movie please reload page again one or more time</th></tr>
      <tr><th>■ If you see the announce "Error loading player: No playable source found", please chat to us in our page facebook <%= link_to "contact us with Facebook", "https://www.facebook.com/messages/movieehdkh" %> </th></tr>
      <tr><th>■ If you see the announce "The video could not be loaded, either because the server or network failed or because the format is not supported.", please use this Add On in your browser chrome <%= link_to "Fix video can not play", "https://chrome.google.com/webstore/detail/zenmate-vpn-best-cyber-se/fdcgdnkidjaadafnichfpabhfomcebme?hl=en" %> </th></tr>
    </thead>
  </table>
</div>

app/views/shared/_coming_soon_movie.html.erb
<li class="hvr-bounce-in">
  <a href="<%= coming_soon_movie.link %>" title="<%= coming_soon_movie.title %>">
    <%= image_tag coming_soon_movie.photo, class: "img-thumbnail resize-photo-movie", title: coming_soon_movie.title %>
  </a>
  <p class="movie-title text-warning"><%= coming_soon_movie.title %></p>
</li>

app/views/shared/_facebook.html.erb
<div class="facebook bagde">
  <%= link_to "https://www.facebook.com/dialog/share?
    app_id=105132389905258&href=#{request.original_url}&redirect_uri=#{request.original_url}" do %>
    <%= image_tag "facebook.png", id: "share-fb" %>
  <% end %>
</div>

app/views/shared/_flooter.html.erb
<footer class="footer">
  <div class="container">
    <hr/>
    <div class="row text-warning" id="flooter">
      <div class="row">
        <div class="col-xs-4">
          <div class="col-xs-12 text-left" id="page-facebook-title"><i class="fa fa-home fa-fw"></i> <%= t "layouts.title" %></div>
          <div class="col-xs-12 text-left">
            <div class="lazy">
              <div class="fb-page" data-href="https://www.facebook.com/movieshdkh/"
                data-width="200" data-hide-cover="false" data-show-facepile="true"
                data-show-posts="false"></div>
              </div>
          </div>
        </div>
        <div class="col-xs-4">
          <div class="col-xs-12">
            <div class="text-center"><i class="fa fa-location-arrow"></i> <%= t "layouts.location" %></div>
            <div class="text-center">Find us on:</div>
          </div>
          <div class="col-xs-12">
            <div class="text-center">
              <div class="social-network">
                <script src="https://apis.google.com/js/platform.js" async defer></script>
                <div class="g-follow" data-annotation="bubble" data-height="20" data-href="//plus.google.com/u/0/106699123530264303390" data-rel="publisher"></div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xs-4">
          <div class="text-rigth"><span>MoviehdKH</span> Provide the movies hd online and free. you can request the movie from our website.</div>
          <div class="text-rigth" id="category-name-footer">
            <% @categories.each do |category| %>
              <span class="badge span_category"><%= link_to category.name, category %></span>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-sm-12 text-warning text-center">
        <span class="badge logo-social"><h5><%= t "disclaimer_policy.title" %></h5></span>
        <p><%= t "disclaimer_policy.body" %></p>
      </div>
    </div>
    <hr/>
    <div class="text-warning text-center"><%= t "layouts.moviehd_kh" %></div>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <%= link_to root_path do %>
        <%= image_tag "logo.png", id: "header-logo", alt: "Moviehd KH" %>
      <% end %>
    </div>
    <div id="navbar" class="navbar-collapse collapse out" aria-expanded="false">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle header-item" data-toggle="dropdown">
            <%= t "layouts.movie" %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <% if @categories.present? %>
              <% @categories.each do |category| %>
                <li class="hvr-grow-shadow"><%= link_to category.name, category_path(category) %></li>
              <% end %>
            <% end %>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle header-item" data-toggle="dropdown">
            <%= t "layouts.year" %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <% if @years.present? %>
              <% @years.each do |year| %>
                <li class="hvr-grow-shadow"><%= link_to year.number, year_path(year) %></li>
              <% end %>
            <% end %>
          </ul>
        </li>
        <li><%= link_to t("layouts.animie"), "http://bakaani.com/", class: "header-item" %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("layouts.request"), "https://www.facebook.com/messages/movieshdkh", class: "header-item" %></li>
        <li><%= link_to t("layouts.search"), searchs_path, class: "header-item" %> </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_main_nav.html.erb
<div id="main-nav" class="text-center">
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <% if @slideshows.present? %>
      <ol class="carousel-indicators">
        <li data-target= "#myCarousel" data-slide-to="0" class="active"></li>
        <% @slideshows.drop(1).each_with_index do |movie, index| %>
          <li data-target="#myCarousel" data-slide-to="<%= index + 1 %>"></li>
        <% end %>
      </ol>

      <div class="carousel-inner slide-img" role="listbox">
        <div class="item active">
          <%= link_to @slideshows.first do %>
            <%= image_tag @slideshows.first.link_cover, class: "slide-img img-responsive" %>
          <% end %>
        </div>
        <% @slideshows.drop(1).each do |movie| %>
          <div class="item">
            <%= link_to movie do %>
              <%= image_tag movie.link_cover, class: "slide-img img-responsive" %>
            <% end %>
          </div>
        <% end %>
      </div>

      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    <% end %>
  </div>
</div>

app/views/shared/_mdgid_advertise.html.erb
<!-- Composite Start -->
<div id="M158446ScriptRootC47325">
    <div id="M158446PreloadC47325">
        Loading...
    </div>
    <script>
                (function(){
            var D=new Date(),d=document,b='body',ce='createElement',ac='appendChild',st='style',ds='display',n='none',gi='getElementById';
            var i=d[ce]('iframe');i[st][ds]=n;d[gi]("M158446ScriptRootC47325")[ac](i);try{var iw=i.contentWindow.document;iw.open();iw.writeln("<ht"+"ml><bo"+"dy></bo"+"dy></ht"+"ml>");iw.close();var c=iw[b];}
            catch(e){var iw=d;var c=d[gi]("M158446ScriptRootC47325");}var dv=iw[ce]('div');dv.id="MG_ID";dv[st][ds]=n;dv.innerHTML=47325;c[ac](dv);
            var s=iw[ce]('script');s.async='async';s.defer='defer';s.charset='utf-8';s.src="//jsc.mgid.com/m/o/moviehdkh.com.47325.js?t="+D.getYear()+D.getMonth()+D.getDate()+D.getHours();c[ac](s);})();
    </script>
</div>
<!-- Composite End -->

app/views/shared/_media_player.html.erb
<div class="text-center">
  <% if @movie.link.sky_drive? %>
    <iframe style="width: 700px; height: 552px; border: 0px;" scrolling="no" src="https://onedrive.live.com/prev?cid=<%= @movie.link.cid %>&amp;id=<%= @movie.link.sky_id %>&amp;authkey=!<%= @movie.link.authkey %>&amp;parId=root&amp;view=video&amp;mode=interactiveEmbed" allowfullscreen="true" webkitallowfullscreen="true" mozallowfullscreen="true"></iframe>
  <% elsif @movie.link.google_plus? || @movie.link.drive? %>
  <div id="extensive" data-default = "<%= @link_default %>" data-hd = "<%= @link_hd %>" data-medium = "<%= @link_medium %>" data-sub = "<%= @movie.link.subtitle %>"></div>
  <% elsif @movie.link.amazon? %>
    <div id="player" data-url="<%= @movie.link.amazon_url %>" ></div>
  <% else %>
    <%= image_tag "logo.png", id: "player_logo" %>
      <iframe src="<%= @movie.link.youtube_embed_link %>" width ="700" height="400" allowfullscreen></iframe>
     <noembed><%= @movie.title %></noembed>
  <% end %>
</div>

app/views/shared/_media_video_js.html.erb
<video id="video" class="video-js vjs-default-skin" controls
 preload="auto" width="700" height="400" autoplay data-setup='{}'>
  <% if @link_video.present? %>
    <% @link_video.each do |link_video| %>
      <source src="<%= link_video.link %>" type="video/mp4" label="<%= link_video.quality %>" data-res="<%= link_video.quality %>">
    <% end %>
  <% end %>
  <% if @movie.link.subtitle.present? %>
    <track label="English" kind="subtitles" srclang="en" src="<%= @movie.link.subtitle %>" default>
  <% end %>
  <p class="vjs-no-js">
    To view this video please enable JavaScript, and consider upgrading to a web browser
    that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
  </p>
</video>
<script type="text/javascript">
  videojs( '#video', { plugins : { resolutionSelector : {
    default_res : "360"
} } } );
</script>

app/views/shared/_pagenator.html.erb
<% if page == 1 %>
  <%= paginate objects, param_name: "page_1",
    params: {page_1: params[:page_1]} %>
<% end %>

app/views/shared/_po_pular_movie.html.erb
<li class="hvr-bounce-in">
  <a href="<%= po_pular_movie.link %>" title="<%= po_pular_movie.title %>">
    <%= image_tag po_pular_movie.photo, class: "img-thumbnail resize-photo-movie", title: po_pular_movie.title %>
  </a>
  <p class="movie-title text-warning"><%= po_pular_movie.title %></p>
</li>

app/views/shared/_request_movie.html.erb
<li class="hvr-bounce-in">
  <a href="<%= request_movie.link %>" title="<%= request_movie.title %>">
    <%= image_tag request_movie.photo, class: "img-thumbnail resize-photo-movie", title: request_movie.title %>
  </a>
  <p class="movie-title text-warning"><%= request_movie.title %></p>
</li>

app/views/shared/_result_search.html.erb
<div class="container">
  <% if @q.conditions.present? %>
    <div class="result-search">
      <h3 class="text-left" id="keyword"><%= t "keyword" %>
        <%= params[:q][:title_cont] %>
      </h3>
      <hr/>
      <% if @movie_searchs.present? %>
        <ul class="list-unstyled list-inline">
          <%  @movie_searchs.each do |movie| %>
            <%= render "movies/movie", movie: movie %>
          <% end %>
        </ul>
        <%= render_pagination @movie_searchs %>
      <% else %>
        <div class="no-result">
          <h2 class="text-left">Nothing Found</h2>
          <h3 class="text-left">
            <%= link_to new_request_path do %>
              <i class="glyphicon glyphicon-hand-right"></i>
                <%= t "click_required" %>
            <% end %>
          </h3>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_revenuehits_advertise.html.erb
<div class="text-center"><script type='text/javascript' src='//clksite.com/adServe/banners?tid=87702_142417_7'></script></div>